# Generated by Django 4.2.7 on 2024-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minesweeper', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GamePrepare',
        ),
        migrations.AddField(
            model_name='difficulty',
            name='Difficultyvalue',
            field=models.CharField(choices=[('easy', '簡單'), ('normal', '普通'), ('hard', '困難')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
