# Generated by Django 5.0 on 2024-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('Documentary', '紀錄片'), ('Music', '音樂片'), ('Animation', '動畫片'), ('Adult', '成人片'), ('Action', '動作片'), ('Sports', '運動片'), ('War', '戰爭片'), ('History', '歷史片'), ('Disaster', '災難片'), ('ScienceFiction', '科幻片'), ('Comedy', '喜劇片'), ('Romance', '愛情片'), ('Horror', '恐怖片'), ('Suspense', '懸疑片'), ('Thriller', '驚悚片')], max_length=20)),
            ],
        ),
    ]
