# Generated by Django 5.0 on 2024-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_genre_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='電影類型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='電影簡介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(choices=[('Documentary', '紀錄片'), ('Music', '音樂片'), ('Animation', '動畫片'), ('Adult', '成人片'), ('Action', '動作片'), ('Sports', '運動片'), ('War', '戰爭片'), ('History', '歷史片'), ('Disaster', '災難片'), ('ScienceFiction', '科幻片'), ('Comedy', '喜劇片'), ('Romance', '愛情片'), ('Horror', '恐怖片'), ('Suspense', '懸疑片'), ('Thriller', '驚悚片')], to='movie.genre', verbose_name='電影類型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie_posters/', verbose_name='電影海報'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='電影上映時間'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='電影名稱'),
        ),
    ]
