# Generated by Django 5.0 on 2024-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_genre_description_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie.genre', verbose_name='電影類型'),
        ),
    ]
