# Generated by Django 5.0 on 2024-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_genres_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtimes',
            field=models.CharField(default='9:00,12:00,15:00,18:00', max_length=100),
        ),
    ]
