# Generated by Django 5.0 on 2024-01-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='showtimes',
        ),
    ]
