# Generated by Django 5.0 on 2024-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_showtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtimes',
            field=models.CharField(default='09:00,12:00,15:00,18:00,21:00', max_length=100),
        ),
    ]
