# Generated by Django 5.0 on 2024-01-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='979-0-00-000000-0', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='lastQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('0', '總類'), ('1', '哲學'), ('2', '宗教'), ('3', '科學'), ('4', '應用科學'), ('5', '社會科學'), ('6', '兩岸史地'), ('7', '世界史地'), ('8', '語言文學'), ('9', '藝術')], default='0', max_length=1),
        ),
    ]
