# Generated by Django 5.0 on 2024-01-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn_book_author_book_lastquantity_book_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
