# Generated by Django 5.0 on 2024-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
