# Generated by Django 5.0 on 2024-01-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='maxQuantity',
            field=models.IntegerField(default=1),
        ),
    ]
