# Generated by Django 4.2.7 on 2024-01-06 03:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('state', models.IntegerField(choices=[(0, '連載中'), (1, '完結')], default=0)),
                ('cover', models.ImageField(upload_to='novel/cover/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Volumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('word_count', models.IntegerField(default=0)),
                ('content', models.FileField(upload_to='novel/chapter/', validators=[django.core.validators.FileExtensionValidator(['txt'])])),
                ('volumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.volumn')),
            ],
        ),
        migrations.CreateModel(
            name='TagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.tag')),
            ],
            options={
                'unique_together': {('novel', 'tag')},
            },
        ),
    ]
